config/routes.rb
Soundtrackshare::Application.routes.draw do

  get '/tag/:name', to: 'tags#show', as: :tag

  resources :posts

  namespace :admin do
    get '/users', to: 'users#index'
  end

  devise_for :users

  resources :users, only: [:show]

  match "about" => 'welcome#about', via: :get

  match "extras" => 'welcome#extras', via: :get

  match "search" => 'welcome#search', via: :get

  match "results" => 'welcome#results', via: :get

  root to: 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts 
    # (or create new ones)
    if user.role? :member
      can :manage, Post, :user_id => user.id
      can :create, Post
    end

    # Admins can do anything
    if user.role? :admin
      can :destroy, Post
      can :destroy, User
      can :manage, :all
      can :read, User
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :tags
  attr_accessible :url, :tag_list, :user_id
  default_scope order("created_at DESC")

  def formatted_url
    url_split = url.split("?v=")
    url_split.length > 1 ? url_split[1] : url
  end

  validates :url, :format => { :with => /youtube.com\/watch\?v=.{11}$/i,
    :message => " - You can only use direct YouTube video page URLs." }, presence: true

  validates :user, presence: true
  validates :tag_list, presence: { message: "was empty OR you didn't use any of the tags below." }

  def self.search(search, filter)
    if search && filter == "true"
      Post.tagged_with(search)
    elsif search
      Post.tagged_with(search, :any => true)
    end
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w[member admin]
  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :name, :can_post

  has_many :posts, dependent: :destroy

  before_create :set_member

  private

  def set_member
    self.role = 'member'
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
    authorize! :read, @users, message: "Only Admins can visit this page."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    authorize! :create, @post, message: "You need create an account first."
  end

  def create
    @post = Post.new
    @post.user_id = current_user.id
    @post.url = params[:post][:url]
    @post.save

    tags = params[:post][:tag_list].split(",").map(&:lstrip)
    tag_names = Tag.all.map{|t| t.name}

    tags.each do |tag|
      tag.downcase!
      @post.tag_list.add(tag) if tag_names.include? tag
    end

    authorize! :create, @post, message: "You need create an account first."
    if @post.save
      flash[:notice] = "Post was saved successfully."
      redirect_to user_path(current_user)
    else
      flash[:error] = "Error creating post. Please try again."
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post, message: "You can't delete this. Scalawag."
    if @post.destroy
      flash[:notice] = "Post was deleted successfully."
      redirect_to current_user
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find_by_name(params[:name])
    @posts = Post.tagged_with(params[:name]).paginate(page: params[:page], per_page: 10) 
    @playlist = @tag.url
    @playlistlink = @playlist.gsub "?", "&feature=share&"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @username = @user.name
    @posts = @user.posts.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def search
    @tags = Tag.all
    @filter = params[:filter]
  end

  def results
    @filter = params[:filter]
    @taglist = params[:tags].downcase
    @posts = Post.search(@taglist, @filter).paginate(page: params[:page], per_page: 10)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def will_paginate(collection_or_options = nil, options = {})
    if collection_or_options.is_a? Hash
      options, collection_or_options = collection_or_options, nil
    end
    unless options[:renderer]
      options = options.merge :renderer => BootstrapLinkRenderer
    end
    super *[collection_or_options, options].compact
  end

  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/index.html.haml
- if can? :read, @users
  .container.text-center
    %h1 All Users
    - @users.each do |u|
      .row.userbox
        .col-sm-offset-3.col-sm-4
          %h3= link_to u.name, user_path(u)
        .col-sm-2{ style: "padding-top: 19px;" }
          - if can? :destroy, u
            = link_to "Delete User", u, method: :delete, class: 'btn btn-danger', confirm: 'Are you sure you want to delete this user?'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SoundtrackShare.io
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %link{href: "http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700", rel: "stylesheet", type: "text/css"}/
  %body
    .container
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", type: "button"} ×
          = flash[:notice]
      - elsif flash[:error]
        .alert.alert-error
          %button.close{"data-dismiss" => "alert", type: "button"} ×
          = flash[:error]
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", type: "button"} ×
          = flash[:alert]
    = yield

app/views/posts/_post.html.haml
.row
  .videobox
    #shared-by
      %small
        Shared by #{link_to post.user.name, user_path(post.user)}
    .text-center
      %iframe{allowfullscreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/#{post.formatted_url}", title: "YouTube video player"}
      %p
        - post.tag_list.each do |t|
          %span.tag= t.capitalize
  .text-center.margin-bottom
    - if can? :destroy, post
      = link_to "Delete Post", post, method: :delete, class: 'btn btn-danger margin-space', confirm: 'Are you sure you want to delete this post?'

app/views/posts/_tagmenu.html.haml
%div{style: "float: left;"}
  %h2.text-center Moods
  .tagbox.margin-bottom-2
    %p
      %span.tag Adventure
      %span.tag Ambient
      %span.tag Angry
      %span.tag Battle
      %span.tag Bittersweet
      %span.tag Building
      %span.tag Celebration
      %span.tag Chase
      %span.tag Comedic
      %span.tag Confidence
      %span.tag Dramatic
      %span.tag Epic
      %span.tag Ethereal
      %span.tag Evil
      %span.tag Excitement
      %span.tag Exploring
      %span.tag Ending
      %span.tag Fantasy
      %span.tag Flying
      %span.tag Happy
      %span.tag Haunting
      %span.tag Hope
      %span.tag Inspirational
      %span.tag Kabuki
      %span.tag Medieval
      %span.tag Melancholy
      %span.tag Mysterious
      %span.tag Nostalgia
      %span.tag Possibilities
      %span.tag Preparing
      %span.tag Relaxed
      %span.tag Romance
      %span.tag Sadness
      %span.tag Sci-Fi
      %span.tag Space
      %span.tag Sports
      %span.tag Tension
      %span.tag Tribal
      %span.tag Victorian
      %span.tag Village
      %span.tag Western
  %h2.text-center Featured Instrument / Sound
  .tagbox.margin-bottom-2
    %p
      %span.tag 8-bit
      %span.tag Accordion
      %span.tag Acoustic Guitar
      %span.tag Brass
      %span.tag Choir
      %span.tag Children's Choir
      %span.tag Distortion
      %span.tag Drums
      %span.tag Electric Guitar
      %span.tag Female Vocal
      %span.tag Flute
      %span.tag Forging
      %span.tag Harp
      %span.tag Horn
      %span.tag Irish Folk
      %span.tag Latin
      %span.tag Male Vocal
      %span.tag Marimba
      %span.tag Strings
      %span.tag Synth
      %span.tag Trumpet
      %span.tag Violin
  %h2.text-center Tempo / Rhythm
  .tagbox.margin-bottom-2
    %p
      %span.tag Anthem
      %span.tag Driving
      %span.tag Galloping
      %span.tag Lilting
      %span.tag March
      %span.tag Offbeat
      %span.tag Punchy

app/views/posts/new.html.haml
.container
  %h1.text-center New Post
  .formbox
    %p.text-center
      Paste an individual YouTube URL for the track you'd like to share (<em>Soundtracks only please</em>) and add tags from <em>only</em> the three menus below. *Tags must be comma-separated*
    = form_for @post, html: {class: "form"} do |f|
      - if @post.errors.any?
        .alert.alert-block
          %h4
            Found #{pluralize(@post.errors.count, "error")}.
          %ul
            - @post.errors.full_messages.each do |msg|
              %li= msg
      = control_group_tag(@post.errors[:url]) do
        .row
          .form-group
            = f.text_field :url, :autofocus => true, class: "form-control input-lg", placeholder: "YouTube URL"
      = control_group_tag(@post.errors[:tag_list]) do
        .row
          .form-group
            = f.text_area :tag_list, class: "form-control input-lg", placeholder: "Tags: comma-separated", rows: 1
      .row
        .form-group
          = f.submit "Save", class: 'btn btn-block btn-large btn-info margin-bottom-2'
  = render "tagmenu"

app/views/tags/show.html.haml
- if @tag
  .container
    %h1.text-center= params[:name].capitalize
    .row
      .videobox.text-center
        .row
          %small.visible-md.visible-lg
            = params[:name].capitalize 
            Playlist
        %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/#{@playlist}", title: "YouTube video player" }
        .row
          %h4.tagbox
            %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=#{@playlistlink}"} Open #{params[:name].capitalize} Playlist in YouTube App
          %div
            = link_to "Extra Playlists", extras_path
    .row
      .text-center.formbox
        = link_to "Share Track", new_post_path, class: "margin-space btn btn-success btn-lg btn-block", id: "share-button"
      .text-center.formbox
        %h4 Community Submissions
    = render @posts
    .text-center
      = will_paginate @posts

:javascript
  $(document).ready( function() {
    $("#share-button").click (function() {
      window.href = $("#share-button").attr("href=posts/new");
    });
  })

app/views/users/show.html.haml
.container
  %h1.text-center
    = @username
    Shares
  .row
    .text-center.formbox
      = link_to "Back to the Home Page", root_path, class: "margin-space btn btn-block btn-default btn-lg"
    .text-center.formbox
      %h4 Community Submissions
  .text-center
    = render @posts
  .row
    .text-center.formbox
      = link_to "Back to the Home Page", root_path, class: "margin-space-2 btn btn-block btn-default btn-lg"
      = will_paginate @posts

app/views/welcome/about.html.haml
%section.text-center.container.col-md-offset-1.col-md-10
  :markdown
    # About the site
    I created this website to share the wealth of original soundtrack pieces I've found over the years from movies, television, and animation. Not only that, but I've also added a rich tagging system and a granular search to help you find the exact mood you are looking for in a piece. I thought this site might be useful to anyone searching for the right mood in a soundtrack piece for a video production, or that it would be nice for anyone who likes listening to OSTs and is trying to discover new soundtrack music.  
    <br/>

    #### **Share Tracks**
    Anyone can add to the collection of tracks by signing up with a username and email address (I don't really care about your info, I just needed a registration system). When you share a track, you'll be encouraged to choose a rich array of tags from the list I've made that are approprate for the feeling that the track conveys. Of course, it's always a subjective choice when tagging your tracks, but I think that most people will recognize the most obvious feelings that a track invokes.  
    <br/>

    #### **Mood Sections**
    The site's structure is pretty simple.  **Click on any of the colored buttons in the main button block on the homepage to view all of the tracks with that button's tag (mood) label.**  For example, if you want to listen to some "Haunting" music, scroll down and find the "Haunting" button.  That will lead you to a page with embedded YouTube videos for each of the community-shared tracks and my own curated playlist.  I chose YouTube as the method for sharing tracks because it has the largest variety of streaming tracks, and it's easy to work with since Google handles all the technical details of streaming.  
    <br/>

    #### **Playlists**
    I am continously adding to my playlists for the 20 different moods in the homepage button block. I recommend that you find a mood that you're interested in listing to and then **open my playlist in YouTube so you can use the shuffle feature.** Then just sit back and discover some great soundtrack music.  The community posts with the corresponding tag are listed underneath this playlist.  
    <br/>

    #### **Advanced Search**
    When you click to go to the "advanced search" page from the link on the homepage, you can search by "any" or "all" of the tags you choose to type in from the ones listed below.  **This search will only return results from the individual community posts, and not from my playlists, so definitely check out my curated playlists one by one.**  
    <br/>

    #### **User Pages**
    The rest of the site is pretty intuitive.  You can click on the username of the person who shared a given track (look for the "Shared by [username]" label on top of the video) to visit their user page, which lists all of their shared tracks.  You should see a delete button under your videos so if you mess up when posting a YouTube video track, you can delete it and try posting it again.  
    <br/>

    ## About Me
    I made this website during my tenure in the [Bloc.io](https://www.bloc.io) web development training program. It showcases some of the skills I learned for building Ruby on Rails applications, and it allowed me to focus on a subject that I am enthusiastic about.
    If you want to talk about this site or share your opinions about soundtrack music, feel free to email me at mpronschinske [+] sts [@] gmail [.] com

app/views/welcome/extras.html.haml
.container
  %h1.text-center Extra Playlists
  .row
    .formbox
      %p.text-center
        This is a list of mood playlists that went over the 200 video limit of YouTube's playlists.  They have songs that were not included in their respective playlists on the mood pages.
  .row
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Battle Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/WyDHkOeICts?list=PLn6gIVVWkLcRJJSD4d9UBdTVlAjj_nE_O", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=#WyDHkOeICts&feature=share&list=PLn6gIVVWkLcRJJSD4d9UBdTVlAjj_nE_O"} Open Battle Playlist 2 in YouTube App
    .margin-bottom
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Bravery Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/qP3CGuBtBGk?list=PLn6gIVVWkLcQJoBLD_Ri5qhzum8vnLPzv", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=qP3CGuBtBGk&feature=share&list=PLn6gIVVWkLcQJoBLD_Ri5qhzum8vnLPzv"} Open Bravery Playlist 2 in YouTube App
    .margin-bottom
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Epic Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/8lnA-msIg34?list=PLn6gIVVWkLcS9qMY-PK749-S_YTwQkRB5", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=8lnA-msIg34&feature=share&list=PLn6gIVVWkLcS9qMY-PK749-S_YTwQkRB5"} Open Epic Playlist 2 in YouTube App
    .margin-bottom
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Hope Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/fedRyexbFHQ?list=PLn6gIVVWkLcRwRCieHe9wi9sfouzXMVSJ", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=fedRyexbFHQ&feature=share&list=PLn6gIVVWkLcRwRCieHe9wi9sfouzXMVSJ"} Open Hope Playlist 2 in YouTube App
    .margin-bottom
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Mysterious Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/yXOCFn9jtx4?list=PLn6gIVVWkLcTBtE7Uq5JDECztpjSK4h1e", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=yXOCFn9jtx4&feature=share&list=PLn6gIVVWkLcTBtE7Uq5JDECztpjSK4h1e"} Open Mysterious Playlist 2 in YouTube App
    .margin-bottom
    .videobox.text-center
      .row
        %small.visible-md.visible-lg
          Tension Playlist 2
      %iframe.visible-md.visible-lg{ allowFullScreen: "true", allowscriptaccess: "always", frameborder: "0", src: "http://www.youtube.com/embed/bqQQEX0qoqM?list=PLn6gIVVWkLcQrXcQ8BQF3CtgGWWyK7odT", title: "YouTube video player" }
      .row
        %h4
          %a.visible-xs.visible-sm{href: "youtube://www.youtube.com/watch?v=bqQQEX0qoqM&feature=share&list=PLn6gIVVWkLcQrXcQ8BQF3CtgGWWyK7odT"} Open Tension Playlist 2 in YouTube App

app/views/welcome/index.html.haml
#fb-root
:javascript
  (function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id;  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=361095707370305"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));

  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

.container
  %h1.text-center SoundtrackShare.io
  .row
    %header.text-center.col-md-offset-2.col-md-8
      %p A soundtrack (OST) music discovery site that features curated soundtrack playlists categorized by mood and community posted tracks with granular tagging.
      %p
        - if current_user
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Sign In", new_user_session_path
          or #{link_to "Sign Up", new_user_registration_path} to share!
        | #{link_to "About", about_path}
      %div
        %a.twitter-share-button{"data-count" => "none", "data-lang" => "en", href: "https://twitter.com/share"} Tweet 
      .fb-share-button{"data-href" => "http://soundtrackshare.herokuapp.com/", "data-type" => "button", "data-width" => "60"}
      %p
        Use the #{link_to "advanced search", search_path} for finding community submitted tracks by mood, or click on one of the mood categories below to find curated playlists.
      - if can? :read, User
        %p= link_to "All Users", admin_users_path
  .row
    .text-center.formbox
      = link_to "Share Track", new_post_path, class: "margin-space btn btn-success btn-lg btn-block"
  .row
    #mood-box.text-center
      = link_to tag_path(name: "adventure"), class: "white-text" do
        .mood-button{style: "background-color: #2ecc71;"} Adventure
      = link_to tag_path(name: "sadness"), class: "white-text" do
        .mood-button{style: "background-color: #3498db;"} Sadness
      = link_to tag_path(name: "epic"), class: "white-text" do
        .mood-button{style: "background-color: #f1c40f;"} Epic
      = link_to tag_path(name: "battle"), class: "white-text" do
        .mood-button{style: "background-color: #e74c3c;"} Battle
      = link_to tag_path(name: "inspirational"), class: "white-text" do
        .mood-button{style: "background-color: #27ae60;"} Inspirational
      = link_to tag_path(name: "bittersweet"), class: "white-text" do
        .mood-button{style: "background-color: #2980b9;"} Bittersweet
      = link_to tag_path(name: "bravery"), class: "white-text" do
        .mood-button{style: "background-color: #f39c12;"} Bravery
      = link_to tag_path(name: "dramatic"), class: "white-text" do
        .mood-button{style: "background-color: #c0392b;"} Dramatic
      = link_to tag_path(name: "possibilities"), class: "white-text" do
        .mood-button{style: "background-color: #30a14e;"} Possibilities
      = link_to tag_path(name: "melancholy"), class: "white-text" do
        .mood-button{style: "background-color: #348fad;"} Melancholy
      = link_to tag_path(name: "hope"), class: "white-text" do
        .mood-button{style: "background-color: #e67e22;"} Hope
      = link_to tag_path(name: "confidence"), class: "white-text" do
        .mood-button{style: "background-color: #b3363c;"} Confidence
      = link_to tag_path(name: "happy"), class: "white-text" do
        .mood-button{style: "background-color: #158f2e;"} Happy
      = link_to tag_path(name: "haunting"), class: "white-text" do
        .mood-button{style: "background-color: #17839c;"} Haunting
      = link_to tag_path(name: "nostalgia"), class: "white-text" do
        .mood-button{style: "background-color: #d35400;"} Nostalgia
      = link_to tag_path(name: "romance"), class: "white-text" do
        .mood-button{style: "background-color: #a11828;"} Romance
      = link_to tag_path(name: "excitement"), class: "white-text" do
        .mood-button{style: "background-color: #2ecc71;"} Excitement
      = link_to tag_path(name: "mysterious"), class: "white-text" do
        .mood-button{style: "background-color: #3498db;"} Mysterious
      = link_to tag_path(name: "tension"), class: "white-text" do
        .mood-button{style: "background-color: #f1c40f;"} Tension
      = link_to tag_path(name: "evil"), class: "white-text" do
        .mood-button{style: "background-color: #e74c3c;"} Evil

app/views/welcome/results.html.haml
.container
  %h1.text-center Results
  .formbox
    %p.text-center If you didn't find any tracks, go back and try using a less strict search. Some tag combinations won't yield any results. *Tags must be comma-separated*
    .form-group
      = form_tag("/results", method: "get") do
        .row
          = text_field_tag(:tags, nil, class: "form-control input-lg", placeholder: "Tags: comma-separated")
        %p.text-center.margin-space
          Match #{select_tag(:filter, options_for_select( [['Any', false], ['All', true]]))} of the Selected Tags
        .row
          = submit_tag("Search", class: "btn btn-block btn-primary btn-lg")
        .row
          %button.btn.btn-block.btn-default.btn-lg.margin-bottom-2{type: "button"}
            = link_to "Back to Search Page", search_path
.container
  = render @posts
  .text-center= will_paginate @posts

app/views/welcome/search.html.haml
.container
  %h1.text-center Search
  .formbox
    %p.text-center
      Type any number of tags from any of the three menus below to find tracks labelled with those tags. *Tags must be comma-separated*
    .form-group
      = form_tag("/results", method: "get") do
        .row
          = text_field_tag(:tags, nil, class: "form-control input-lg", placeholder: "Tags: comma-separated")
        %p.text-center.margin-space
          Match #{select_tag(:filter, options_for_select([['Any', false], ['All', true]]))} of the Selected Tags
        .row
          = submit_tag("Search", class: "btn btn-block btn-primary btn-lg")
        .row
          %button.btn.btn-block.btn-default.btn-lg.margin-bottom-2{type: "button"}
            = link_to "Back to the Home Page", root_path
  = render "posts/tagmenu"